### ISSUE TITLE
Discuss tech stack

### ISSUE THREAD

**Issue by margoflewelling** [Hifu-devs/hifu-api#2]
- [ ] Research implementing graphql in ruby
- [ ] Research scheduling jobs
- [ ] Deployment / CI  (heroku, travis)
- [ ] Local setup, pull down repos

**Comment by brian-greeson** [comment]
Implementing [heroku job scheduler](https://devcenter.heroku.com/articles/scheduler) Looks like a viable way for use to initiate the emergency emails. 
Another [Example](https://medium.com/@zayneabraham/creating-simple-automated-jobs-in-heroku-with-rails-and-scheduler-41cce4efdcc7)

TLDR: we setup a rake task that will be run periodically by a free heroku plugin
