### ISSUE TITLE
Trigger Contact Microservices

### ISSUE THREAD

**Issue by brian-greeson** [Hifu-devs/hifu-api#24]
### As a contact microservice, when a route's end_time has past, I need the following information posted to my endpoint, so that I can contact the user's emergency contact.

- SMS 
  - Endpoint address: 
    - https://hifu-sms.herokuapp.com/alert
  - required info
    - phone number to send to ("phone")
    -  name of person lost ("name")
    - activity they were doing ("activity")
    - email address of friend ("email")

- Email required info
  - Endpoint address: 
    - < endpoint >
  - required info
    - < stuff >
    - < things >

**Comment by kristastadler** [comment]
Example of what the SMS microservice is looking for in a post request:

![Screen Shot 2020-07-18 at 7 43 11 PM](https://user-images.githubusercontent.com/56809375/87865166-f5ef4a00-c92e-11ea-9254-6bdc7efb97a6.png)

**Comment by kristastadler** [comment]
The Twilio service is also set up to send and receive texts to/from any phone number :)
Our Hifu phone number is: `+1 334 471 4617`
