### ISSUE TITLE
DB schema

### ISSUE THREAD

**Issue by margoflewelling** [Hifu-devs/hifu-api#3]
- [x] Make ERD diagram 
  - [Diagram](https://dbdiagram.io/d/5f0f424e74ca2227330d653e)

**Comment by brian-greeson** [comment]
<img width="1311" alt="Screen Shot 2020-07-15 at 6 50 31 PM" src="https://user-images.githubusercontent.com/3604068/87613991-18355d80-c6cc-11ea-9875-e67ce5ce63ef.png">

**Comment by brian-greeson** [comment]
<img width="1025" alt="Screen Shot 2020-07-18 at 10 12 04 PM" src="https://user-images.githubusercontent.com/3604068/87866856-bf6ffa00-c943-11ea-848f-e5c071afe3e0.png">

**Comment by brian-greeson** [comment]
<img width="1093" alt="Screen Shot 2020-07-23 at 12 52 14 PM" src="https://user-images.githubusercontent.com/3604068/88326523-5db4e480-cce3-11ea-81aa-5cce9894cd60.png">
