### ISSUE TITLE
GraphQL Spike

### ISSUE THREAD

**Issue by brian-greeson** [Hifu-devs/hifu-api#6]
# Requirements

### User(email_address:){
  - Route
    - Waypoints
    - Contacts
}

### Create( {
 - User
  - Route
    - Waypoints
    - Contacts
}){
### User {
  - Route
    - Waypoints
    - Contacts
}

- Destroy(email_address:){ status: deleted }

**Comment by kristastadler** [comment]
Docs: https://graphql-ruby.org/
And the Getting Started Guide with info on how to use rails g to create objects: https://graphql-ruby.org/getting_started
